In [0]:
from time import time
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import offsetbox
from sklearn import (manifold, datasets, decomposition, ensemble,
                     discriminant_analysis, random_projection, neighbors)
!pip install hdf5storage
import hdf5storage
from sklearn.model_selection import train_test_split
from matplotlib import offsetbox
from sklearn import (manifold, datasets, decomposition, ensemble,
                     discriminant_analysis, random_projection, neighbors)
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
Data_Foldername = '/content/drive/My Drive/CSIC Project'

Data_X =    "%s/file.mat" % (Data_Foldername)
Dala_Y =    "%s/label.mat" % (Data_Foldername)

X=hdf5storage.loadmat(Data_X)
Y=hdf5storage.loadmat(Dala_Y)
X1=X['Files']
Y1=Y['label']

In [0]:
def plot_embedding(X, title=None):

    plt.scatter(X[:,0],X[:,1],c=Y1)
    plt.colorbar()

    if title is not None:
        plt.title(title)

In [0]:
#calculation for KNN
def KNN(X, kn):
 X_train, X_test, y_train, y_test = train_test_split(X, Y1, test_size=0.20, random_state = 42)
 from sklearn.preprocessing import StandardScaler
 scaler = StandardScaler()
 scaler.fit(X_train)
 X_train = scaler.transform(X_train)
 X_test = scaler.transform(X_test)
 neigh = KNeighborsClassifier(n_neighbors=kn)
 neigh.fit(X_train, y_train)
 y_pred = neigh.predict(X_test)
 print(confusion_matrix(y_test, y_pred))
 print(classification_report(y_test, y_pred))

In [0]:
for i in range(100):
  import random
  random.seed(i)
  shuffling_index =random.sample(range(Y1.size),Y1.size);
  X1 = X1[shuffling_index,:]
  Y1 =  Y1[shuffling_index,:]
  print("Computing MDS embedding")
  clf = manifold.MDS(n_components=2, n_init=1, max_iter=100)
  t0 = time()
  X_mds = clf.fit_transform(X1)
  print("Done. Stress: %f" % clf.stress_)
  plot_embedding(X_mds,
               "MDS (time %.2fs)" %
               (time() - t0))
  KNN(X_mds,5)
  
  

Computing MDS embedding
Done. Stress: 229023162423144.906250
[[951  42]
 [ 51 956]]
              precision    recall  f1-score   support

           0       0.95      0.96      0.95       993
           1       0.96      0.95      0.95      1007

    accuracy                           0.95      2000
   macro avg       0.95      0.95      0.95      2000
weighted avg       0.95      0.95      0.95      2000



/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.


Computing MDS embedding
Done. Stress: 229015644846730.250000
[[939  42]
 [ 49 970]]
              precision    recall  f1-score   support

           0       0.95      0.96      0.95       981
           1       0.96      0.95      0.96      1019

    accuracy                           0.95      2000
   macro avg       0.95      0.95      0.95      2000
weighted avg       0.95      0.95      0.95      2000



/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.


Computing MDS embedding
Done. Stress: 228897120117607.718750
[[953  30]
 [ 52 965]]
              precision    recall  f1-score   support

           0       0.95      0.97      0.96       983
           1       0.97      0.95      0.96      1017

    accuracy                           0.96      2000
   macro avg       0.96      0.96      0.96      2000
weighted avg       0.96      0.96      0.96      2000



/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.


Computing MDS embedding
Done. Stress: 228779484434786.062500
[[920  35]
 [ 62 983]]
              precision    recall  f1-score   support

           0       0.94      0.96      0.95       955
           1       0.97      0.94      0.95      1045

    accuracy                           0.95      2000
   macro avg       0.95      0.95      0.95      2000
weighted avg       0.95      0.95      0.95      2000



/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.


Computing MDS embedding
Done. Stress: 228945693656865.062500
[[978  52]
 [ 51 919]]
              precision    recall  f1-score   support

           0       0.95      0.95      0.95      1030
           1       0.95      0.95      0.95       970

    accuracy                           0.95      2000
   macro avg       0.95      0.95      0.95      2000
weighted avg       0.95      0.95      0.95      2000



/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.


Computing MDS embedding
Done. Stress: 228939267063020.187500
[[965  40]
 [ 48 947]]
              precision    recall  f1-score   support

           0       0.95      0.96      0.96      1005
           1       0.96      0.95      0.96       995

    accuracy                           0.96      2000
   macro avg       0.96      0.96      0.96      2000
weighted avg       0.96      0.96      0.96      2000



/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.


Computing MDS embedding
Done. Stress: 228874143611732.218750
[[962  41]
 [ 55 942]]
              precision    recall  f1-score   support

           0       0.95      0.96      0.95      1003
           1       0.96      0.94      0.95       997

    accuracy                           0.95      2000
   macro avg       0.95      0.95      0.95      2000
weighted avg       0.95      0.95      0.95      2000



/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.


Computing MDS embedding
Done. Stress: 229044149324652.375000
[[956  40]
 [ 60 944]]
              precision    recall  f1-score   support

           0       0.94      0.96      0.95       996
           1       0.96      0.94      0.95      1004

    accuracy                           0.95      2000
   macro avg       0.95      0.95      0.95      2000
weighted avg       0.95      0.95      0.95      2000



/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.


Computing MDS embedding
Done. Stress: 228946894504749.937500
[[935  40]
 [ 54 971]]
              precision    recall  f1-score   support

           0       0.95      0.96      0.95       975
           1       0.96      0.95      0.95      1025

    accuracy                           0.95      2000
   macro avg       0.95      0.95      0.95      2000
weighted avg       0.95      0.95      0.95      2000



/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.


Computing MDS embedding
Done. Stress: 229064239250679.812500
[[935  37]
 [ 66 962]]
              precision    recall  f1-score   support

           0       0.93      0.96      0.95       972
           1       0.96      0.94      0.95      1028

    accuracy                           0.95      2000
   macro avg       0.95      0.95      0.95      2000
weighted avg       0.95      0.95      0.95      2000



/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.


Computing MDS embedding
Done. Stress: 228810335170682.312500
[[984  35]
 [ 49 932]]
              precision    recall  f1-score   support

           0       0.95      0.97      0.96      1019
           1       0.96      0.95      0.96       981

    accuracy                           0.96      2000
   macro avg       0.96      0.96      0.96      2000
weighted avg       0.96      0.96      0.96      2000



/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.


Computing MDS embedding
Done. Stress: 228921230092531.531250
[[963  52]
 [ 49 936]]
              precision    recall  f1-score   support

           0       0.95      0.95      0.95      1015
           1       0.95      0.95      0.95       985

    accuracy                           0.95      2000
   macro avg       0.95      0.95      0.95      2000
weighted avg       0.95      0.95      0.95      2000



/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.


Computing MDS embedding
Done. Stress: 229005672137831.843750
[[961  34]
 [ 64 941]]
              precision    recall  f1-score   support

           0       0.94      0.97      0.95       995
           1       0.97      0.94      0.95      1005

    accuracy                           0.95      2000
   macro avg       0.95      0.95      0.95      2000
weighted avg       0.95      0.95      0.95      2000



/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.


Computing MDS embedding
Done. Stress: 229161179726870.093750
[[970  42]
 [ 53 935]]
              precision    recall  f1-score   support

           0       0.95      0.96      0.95      1012
           1       0.96      0.95      0.95       988

    accuracy                           0.95      2000
   macro avg       0.95      0.95      0.95      2000
weighted avg       0.95      0.95      0.95      2000



/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.


Computing MDS embedding
Done. Stress: 229040199455861.687500
[[934  48]
 [ 46 972]]
              precision    recall  f1-score   support

           0       0.95      0.95      0.95       982
           1       0.95      0.95      0.95      1018

    accuracy                           0.95      2000
   macro avg       0.95      0.95      0.95      2000
weighted avg       0.95      0.95      0.95      2000



/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.


Computing MDS embedding
