In [0]:
from time import time
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import offsetbox
from sklearn import (manifold, datasets, decomposition, ensemble,
                     discriminant_analysis, random_projection, neighbors)
!pip install hdf5storage
import hdf5storage
from sklearn.model_selection import train_test_split
from matplotlib import offsetbox
from sklearn import (manifold, datasets, decomposition, ensemble,
                     discriminant_analysis, random_projection, neighbors)
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
Data_Foldername = '/content/drive/My Drive/CSIC Project'

Data_X =    "%s/file.mat" % (Data_Foldername)
Dala_Y =    "%s/label.mat" % (Data_Foldername)

X=hdf5storage.loadmat(Data_X)
Y=hdf5storage.loadmat(Dala_Y)
X1=X['Files']
Y1=Y['label']

In [0]:
def plot_embedding(X, title=None):

    plt.scatter(X[:,0],X[:,1],c=Y1)
    plt.colorbar()

    if title is not None:
        plt.title(title)

In [0]:
#calculation for KNN
def KNN(X, kn):
 X_train, X_test, y_train, y_test = train_test_split(X, Y1, test_size=0.50, random_state = 42)
 from sklearn.preprocessing import StandardScaler
 scaler = StandardScaler()
 scaler.fit(X_train)
 X_train = scaler.transform(X_train)
 X_test = scaler.transform(X_test)
 neigh = KNeighborsClassifier(n_neighbors=kn)
 neigh.fit(X_train, y_train)
 y_pred = neigh.predict(X_test)
 print(confusion_matrix(y_test, y_pred))
 print(classification_report(y_test, y_pred))

In [0]:
for i in range(10):
 import random
 random.seed(30)
 n_components=i*2+2
 shuffling_index =random.sample(range(Y1.size),Y1.size);
 X1 = X1[shuffling_index,:]
 Y1 =  Y1[shuffling_index,:]
 print("Computing MDS embedding")
 clf = manifold.MDS(n_components, n_init=1, max_iter=100)
 t0 = time()
 X_mds = clf.fit_transform(X1)
 print("Done. Stress: %f "% clf.stress_, "number of components: %d" %n_components)
 #plot_embedding(X_mds, "MDS (time %.2fs)" %     (time() - t0))
 KNN(X_mds,5)

Computing MDS embedding
Done. Stress: 228831897154632.250000  number of components: 2
[[2439   90]
 [ 141 2330]]
              precision    recall  f1-score   support

           0       0.95      0.96      0.95      2529
           1       0.96      0.94      0.95      2471

    accuracy                           0.95      5000
   macro avg       0.95      0.95      0.95      5000
weighted avg       0.95      0.95      0.95      5000



/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.


Computing MDS embedding
Done. Stress: 93866456924011.500000  number of components: 4


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.


[[2445   94]
 [ 151 2310]]
              precision    recall  f1-score   support

           0       0.94      0.96      0.95      2539
           1       0.96      0.94      0.95      2461

    accuracy                           0.95      5000
   macro avg       0.95      0.95      0.95      5000
weighted avg       0.95      0.95      0.95      5000

Computing MDS embedding
Done. Stress: 59282299676055.054688  number of components: 6


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.


[[2463   59]
 [ 261 2217]]
              precision    recall  f1-score   support

           0       0.90      0.98      0.94      2522
           1       0.97      0.89      0.93      2478

    accuracy                           0.94      5000
   macro avg       0.94      0.94      0.94      5000
weighted avg       0.94      0.94      0.94      5000

Computing MDS embedding
Done. Stress: 44404894210026.109375  number of components: 8


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.


[[2484   36]
 [ 386 2094]]
              precision    recall  f1-score   support

           0       0.87      0.99      0.92      2520
           1       0.98      0.84      0.91      2480

    accuracy                           0.92      5000
   macro avg       0.92      0.92      0.92      5000
weighted avg       0.92      0.92      0.92      5000

Computing MDS embedding
Done. Stress: 35647938028623.968750  number of components: 10


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.


[[2469   31]
 [ 493 2007]]
              precision    recall  f1-score   support

           0       0.83      0.99      0.90      2500
           1       0.98      0.80      0.88      2500

    accuracy                           0.90      5000
   macro avg       0.91      0.90      0.89      5000
weighted avg       0.91      0.90      0.89      5000

Computing MDS embedding
Done. Stress: 30295503289474.457031  number of components: 12


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.


[[2525   18]
 [ 586 1871]]
              precision    recall  f1-score   support

           0       0.81      0.99      0.89      2543
           1       0.99      0.76      0.86      2457

    accuracy                           0.88      5000
   macro avg       0.90      0.88      0.88      5000
weighted avg       0.90      0.88      0.88      5000

Computing MDS embedding
Done. Stress: 26467626957434.191406  number of components: 14


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.


[[2460   16]
 [ 699 1825]]
              precision    recall  f1-score   support

           0       0.78      0.99      0.87      2476
           1       0.99      0.72      0.84      2524

    accuracy                           0.86      5000
   macro avg       0.89      0.86      0.85      5000
weighted avg       0.89      0.86      0.85      5000

Computing MDS embedding
Done. Stress: 23399098610988.652344  number of components: 16


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.


[[2522   11]
 [ 785 1682]]
              precision    recall  f1-score   support

           0       0.76      1.00      0.86      2533
           1       0.99      0.68      0.81      2467

    accuracy                           0.84      5000
   macro avg       0.88      0.84      0.84      5000
weighted avg       0.88      0.84      0.84      5000

Computing MDS embedding
Done. Stress: 21332627603468.281250  number of components: 18


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.


[[2520    9]
 [ 950 1521]]
              precision    recall  f1-score   support

           0       0.73      1.00      0.84      2529
           1       0.99      0.62      0.76      2471

    accuracy                           0.81      5000
   macro avg       0.86      0.81      0.80      5000
weighted avg       0.86      0.81      0.80      5000

Computing MDS embedding
Done. Stress: 19776883027425.519531  number of components: 20


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.


[[2518    9]
 [1005 1468]]
              precision    recall  f1-score   support

           0       0.71      1.00      0.83      2527
           1       0.99      0.59      0.74      2473

    accuracy                           0.80      5000
   macro avg       0.85      0.80      0.79      5000
weighted avg       0.85      0.80      0.79      5000

